apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: google-drive-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size based on your needs
